// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQRJLDpSpbY-MSwl2vlIvY2lx6Vsh-vXk',
    appId: '1:1089941988804:web:56960535a9022058cc7091',
    messagingSenderId: '1089941988804',
    projectId: 'to-do-list-firestore-964a1',
    authDomain: 'to-do-list-firestore-964a1.firebaseapp.com',
    storageBucket: 'to-do-list-firestore-964a1.appspot.com',
    measurementId: 'G-7PPE9NFVZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3j1hMsYeF0ClWS80bk-LU2I4_33CbZM',
    appId: '1:1089941988804:android:17fd4046b2618cdbcc7091',
    messagingSenderId: '1089941988804',
    projectId: 'to-do-list-firestore-964a1',
    storageBucket: 'to-do-list-firestore-964a1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQRJLDpSpbY-MSwl2vlIvY2lx6Vsh-vXk',
    appId: '1:1089941988804:web:a918e988bdbaa74ccc7091',
    messagingSenderId: '1089941988804',
    projectId: 'to-do-list-firestore-964a1',
    authDomain: 'to-do-list-firestore-964a1.firebaseapp.com',
    storageBucket: 'to-do-list-firestore-964a1.appspot.com',
    measurementId: 'G-FS6XFD7SGE',
  );
}
